---
nats_uri: nats://10.168.3.189:4222
mysql:
  host: 10.168.3.163
  port: 3306
  username: root
  password: 123
mysql_admin: http://phpadmin.zhaodch.cf2.youdao.com/index.php

stats_uri: http://varz:varz@10.168.3.155:54321/varz

svn:
  app_base: #
  template_base: #
  local_base: #
  username: #
  password: #
